from fpdf import FPDF, XPos, YPos
from datetime import datetime
from textblob import TextBlob
import os
import logging

logger = logging.getLogger(__name__)


# ─── Text Sanitizer ───────────────────────────────────────────────────────────
def _sanitize_text(text):
    """Replace common non-latin-1 Unicode characters to prevent FPDF2 crashes."""
    if not text:
        return ""
    replacements = {
        '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
        '\u2013': '-', '\u2014': '-', '\u2022': '*', '\u2026': '...',
        '\u00a0': ' ',
    }
    for uni_char, replacement in replacements.items():
        text = text.replace(uni_char, replacement)
    return text.encode('latin-1', errors='replace').decode('latin-1')


# ─── Color helpers ────────────────────────────────────────────────────────────
PRIMARY   = (0,  135, 200)   # blue accent
DARK      = (20,  30,  50)   # near-black for headings
GREY      = (90, 100, 115)   # secondary text
LIGHT_BG  = (245, 247, 250)  # section background
WHITE     = (255, 255, 255)


class MeetingReportPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def __init__(self, report_title="Meeting Intelligence Report"):
        super().__init__()
        self.report_title = report_title

    def header(self):
        # Dark top bar
        self.set_fill_color(*DARK)
        self.rect(0, 0, 210, 14, style='F')
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(*WHITE)
        self.set_xy(10, 3)
        self.cell(130, 8, self.report_title, align='L')
        self.set_xy(140, 3)
        self.set_font('Helvetica', '', 8)
        self.cell(60, 8, datetime.now().strftime('%B %d, %Y'), align='R')
        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-14)
        self.set_fill_color(*DARK)
        self.rect(0, self.get_y(), 210, 14, style='F')
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*WHITE)
        self.cell(95, 10, 'Generated by Meeting AI Pro', align='L')
        self.cell(95, 10, f'Page {self.page_no()}', align='R')
        self.set_text_color(0, 0, 0)

    # ── Section helpers ───────────────────────────────────────
    def section_header(self, icon_char, title, color=PRIMARY):
        """Renders a coloured left-bar section title."""
        self.ln(4)
        # Accent bar
        self.set_fill_color(*color)
        self.rect(self.get_x(), self.get_y(), 3, 8, style='F')
        self.set_x(self.get_x() + 5)
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(*DARK)
        self.cell(0, 8, f"{icon_char}  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def hr(self):
        self.set_draw_color(*PRIMARY)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def kv_row(self, label, value, shade=False):
        """Renders a two-column key-value row, optionally shaded."""
        if shade:
            self.set_fill_color(*LIGHT_BG)
            self.rect(10, self.get_y(), 190, 7, style='F')
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(*GREY)
        self.set_x(12)
        self.cell(55, 7, label, align='L')
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*DARK)
        self.cell(130, 7, str(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def bullet_item(self, index, text, shade=False):
        if shade:
            self.set_fill_color(*LIGHT_BG)
            self.rect(10, self.get_y(), 190, 8, style='F')
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(*PRIMARY)
        self.set_x(12)
        self.cell(8, 8, f"{index}.")
        self.set_font('Helvetica', '', 9)
        self.set_text_color(*DARK)
        self.multi_cell(172, 8, text)
        self.ln(1)


# ─── Public API ───────────────────────────────────────────────────────────────
def save_meeting_pdf(
    transcript,
    summary,
    filepath,
    title="Meeting Intelligence Report",
    action_items=None,
    username=None,
    audio_filename=None,
):
    """
    Save a full professional meeting intelligence report as PDF.

    Sections:
      1. Cover header (meta-data)
      2. Executive Summary
      3. Action Items
      4. Sentiment & Text Analytics
      5. Full Transcript
    """
    try:
        # Sanitise
        title          = _sanitize_text(title)
        transcript     = _sanitize_text(transcript)
        summary        = _sanitize_text(summary)
        action_items   = [_sanitize_text(a) for a in (action_items or [])]
        username       = _sanitize_text(username or "N/A")
        audio_filename = _sanitize_text(audio_filename or "N/A")

        # Derive analytics
        words    = transcript.split()
        wc       = len(words)
        cc       = len(transcript)
        sents    = [s.strip() for s in transcript.split('.') if s.strip()]
        sc       = len(sents)

        try:
            blob        = TextBlob(transcript)
            polarity    = blob.sentiment.polarity
            subjectivity= blob.sentiment.subjectivity
            sentiment   = ("Positive" if polarity > 0.1
                           else "Negative" if polarity < -0.1
                           else "Neutral")
        except Exception:
            polarity = subjectivity = 0.0
            sentiment = "N/A"

        # ── Build PDF ──────────────────────────────────────────
        pdf = MeetingReportPDF(report_title=title)
        pdf.set_auto_page_break(auto=True, margin=18)

        # ═══════════════════════════════════════════════════════
        # PAGE 1 – Cover + Summary + Actions
        # ═══════════════════════════════════════════════════════
        pdf.add_page()

        # Hero title block
        pdf.set_fill_color(*PRIMARY)
        pdf.rect(10, pdf.get_y(), 190, 28, style='F')
        pdf.set_font('Helvetica', 'B', 22)
        pdf.set_text_color(*WHITE)
        pdf.set_xy(14, pdf.get_y() + 4)
        pdf.cell(182, 10, title, align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font('Helvetica', '', 10)
        pdf.set_x(14)
        pdf.cell(182, 10, 'Automated Meeting Intelligence Report', align='C',
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(6)

        # Metadata table
        pdf.section_header('[i]', 'Report Metadata')
        pdf.hr()
        meta = [
            ("Generated on",   datetime.now().strftime('%Y-%m-%d  %H:%M:%S')),
            ("Recorded by",    username),
            ("Audio file",     audio_filename),
            ("Word count",     f"{wc:,}  words"),
            ("Duration est.",  f"~{max(1, wc // 130)} min"),
        ]
        for i, (k, v) in enumerate(meta):
            pdf.kv_row(k, v, shade=(i % 2 == 0))
        pdf.ln(4)

        # Executive Summary
        pdf.section_header('[S]', 'Executive Summary')
        pdf.hr()
        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(*DARK)
        for para in summary.split('\n'):
            if para.strip():
                pdf.multi_cell(190, 6, para.strip())
                pdf.ln(2)
        pdf.ln(4)

        # Action Items
        pdf.section_header('[A]', 'Action Items')
        pdf.hr()
        if action_items:
            for i, item in enumerate(action_items, 1):
                pdf.bullet_item(i, item, shade=(i % 2 == 0))
        else:
            pdf.set_font('Helvetica', 'I', 9)
            pdf.set_text_color(*GREY)
            pdf.cell(0, 7, "No action items detected.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(4)

        # ═══════════════════════════════════════════════════════
        # PAGE 2 – Analytics + Full Transcript
        # ═══════════════════════════════════════════════════════
        pdf.add_page()

        # Analytics section
        pdf.section_header('[~]', 'Sentiment & Text Analytics')
        pdf.hr()
        analytics = [
            ("Sentiment",      sentiment),
            ("Polarity score", f"{polarity:.3f}  (-1.0 very negative  ...  +1.0 very positive)"),
            ("Subjectivity",   f"{subjectivity:.3f}  (0.0 fully objective  ...  1.0 fully subjective)"),
            ("Total words",    f"{wc:,}"),
            ("Total characters", f"{cc:,}"),
            ("Sentence count", f"{sc}"),
            ("Avg words/sent", f"{wc // max(sc, 1)}"),
        ]
        for i, (k, v) in enumerate(analytics):
            pdf.kv_row(k, v, shade=(i % 2 == 0))
        pdf.ln(6)

        # Full transcript
        pdf.section_header('[T]', 'Full Transcript')
        pdf.hr()
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(*DARK)
        # Print sentence-by-sentence with light shading every other line
        for i, sent in enumerate(sents):
            if i % 2 == 0:
                self_y = pdf.get_y()
                pdf.set_fill_color(*LIGHT_BG)
                pdf.rect(10, self_y, 190, 6, style='F')
            pdf.set_x(12)
            pdf.multi_cell(186, 6, sent.strip() + '.')
        pdf.ln(4)

        # ── Save ──────────────────────────────────────────────
        os.makedirs(os.path.dirname(filepath) or '.', exist_ok=True)
        pdf.output(filepath)
        logger.info("PDF saved successfully: %s", filepath)
        return True

    except Exception as e:
        logger.error("Error saving PDF to %s: %s", filepath, str(e))
        return False
